using Hazina.AI.CognitivePipeline.Core;

namespace Hazina.AI.CognitivePipeline.Learning;

/// <summary>
/// Learning engine for the SCP cognitive pipeline.
/// Implements the DBTL (Design-Build-Test-Learn) loop:
/// records pipeline outcomes, identifies patterns, and applies improvements.
/// </summary>
public interface ICognitiveLearningEngine
{
    /// <summary>
    /// Record the outcome of a pipeline execution for future learning.
    /// </summary>
    Task RecordOutcomeAsync(CognitivePipelineResult result, CancellationToken cancellationToken = default);

    /// <summary>
    /// Analyze recorded outcomes to discover patterns and generate improvement recommendations.
    /// </summary>
    Task<LearningInsights> LearnAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Apply learned improvements to a pipeline configuration.
    /// Adjusts stage weights, thresholds, and other parameters based on past performance.
    /// </summary>
    Task<CognitivePipelineConfig> ApplyLearnedImprovementsAsync(
        CognitivePipelineConfig currentConfig,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Insights generated by the learning engine from analyzing pipeline outcomes.
/// </summary>
public class LearningInsights
{
    /// <summary>
    /// Total number of pipeline executions analyzed.
    /// </summary>
    public int ExecutionsAnalyzed { get; set; }

    /// <summary>
    /// Average final confidence across all executions.
    /// </summary>
    public double AverageConfidence { get; set; }

    /// <summary>
    /// Average noise reduction rate across all executions.
    /// </summary>
    public double AverageNoiseReductionRate { get; set; }

    /// <summary>
    /// Average GroundTruth hit rate across all executions.
    /// </summary>
    public double AverageGroundTruthHitRate { get; set; }

    /// <summary>
    /// Recommended weight adjustments for Decision stage synthesis.
    /// </summary>
    public Dictionary<string, double> RecommendedWeights { get; set; } = new();

    /// <summary>
    /// Specific improvement recommendations.
    /// </summary>
    public List<string> Recommendations { get; set; } = new();

    /// <summary>
    /// Stages that consistently underperform.
    /// </summary>
    public List<string> UnderperformingStages { get; set; } = new();

    /// <summary>
    /// Facts that should be promoted to GroundTruth (verified 3+ times with >90% confidence).
    /// </summary>
    public int FactsReadyForPromotion { get; set; }
}
