// <auto-generated />
using System;
using Hazina.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hazina.Data.Migrations
{
    [DbContext(typeof(GeometricReasoningDbContext))]
    partial class GeometricReasoningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hazina.Core.Entities.Geometric.Concept", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BaseConfusion")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<string>("ConceptId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastPracticedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LocalCurvature")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("MasteryLevel")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PositionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PracticeCount")
                        .HasColumnType("int");

                    b.Property<string>("ThoughtSpaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LastPracticedAt")
                        .HasDatabaseName("IX_Concepts_LastPracticedAt");

                    b.HasIndex("ThoughtSpaceId")
                        .HasDatabaseName("IX_Concepts_ThoughtSpaceId");

                    b.HasIndex("ThoughtSpaceId", "ConceptId")
                        .IsUnique()
                        .HasDatabaseName("IX_Concepts_ThoughtSpaceConceptId");

                    b.ToTable("Concepts");

                    b.HasData(
                        new
                        {
                            Id = "concept-variables",
                            BaseConfusion = 0.5m,
                            ConceptId = "variables",
                            CreatedAt = new DateTime(2026, 2, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Understanding variable declaration, assignment, and different data types",
                            LastPracticedAt = new DateTime(2026, 2, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            LocalCurvature = 0.15m,
                            MasteryLevel = 0.7m,
                            Name = "Variables and Data Types",
                            PositionJson = "[0.2, 0.3, 0.1, 0.4, 0.5, 0.2, 0.3, 0.4, 0.1, 0.2, 0.3, 0.2]",
                            PracticeCount = 10,
                            ThoughtSpaceId = "ts-example-programming",
                            UpdatedAt = new DateTime(2026, 2, 19, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "concept-functions",
                            BaseConfusion = 1.2m,
                            ConceptId = "functions",
                            CreatedAt = new DateTime(2026, 2, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Understanding function definitions, parameters, return values, and scope",
                            LastPracticedAt = new DateTime(2026, 2, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            LocalCurvature = 0.72m,
                            MasteryLevel = 0.4m,
                            Name = "Functions and Methods",
                            PositionJson = "[0.4, 0.5, 0.3, 0.6, 0.7, 0.4, 0.5, 0.6, 0.3, 0.4, 0.5, 0.4]",
                            PracticeCount = 5,
                            ThoughtSpaceId = "ts-example-programming",
                            UpdatedAt = new DateTime(2026, 2, 18, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "concept-algorithms",
                            BaseConfusion = 2.5m,
                            ConceptId = "algorithms",
                            CreatedAt = new DateTime(2026, 2, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Understanding algorithmic thinking, sorting, searching, and optimization",
                            LastPracticedAt = new DateTime(2026, 2, 17, 16, 0, 0, 0, DateTimeKind.Utc),
                            LocalCurvature = 2.25m,
                            MasteryLevel = 0.1m,
                            Name = "Algorithms and Problem Solving",
                            PositionJson = "[0.7, 0.8, 0.6, 0.9, 1.0, 0.7, 0.8, 0.9, 0.6, 0.7, 0.8, 0.7]",
                            PracticeCount = 2,
                            ThoughtSpaceId = "ts-example-programming",
                            UpdatedAt = new DateTime(2026, 2, 17, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Hazina.Core.Entities.Geometric.ConceptConnection", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromConceptId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Strength")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<string>("ToConceptId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromConceptId")
                        .HasDatabaseName("IX_ConceptConnections_FromConcept");

                    b.HasIndex("ToConceptId")
                        .HasDatabaseName("IX_ConceptConnections_ToConcept");

                    b.HasIndex("FromConceptId", "ToConceptId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConceptConnections_FromTo");

                    b.ToTable("ConceptConnections");

                    b.HasData(
                        new
                        {
                            Id = "conn-var-to-func",
                            CreatedAt = new DateTime(2026, 2, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            FromConceptId = "concept-variables",
                            Reason = "Understanding variables is essential before learning functions",
                            Strength = 0.9m,
                            ToConceptId = "concept-functions",
                            Type = 0
                        },
                        new
                        {
                            Id = "conn-func-to-algo",
                            CreatedAt = new DateTime(2026, 2, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            FromConceptId = "concept-functions",
                            Reason = "Functions are the building blocks for implementing algorithms",
                            Strength = 0.95m,
                            ToConceptId = "concept-algorithms",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Hazina.Core.Entities.Geometric.LearningEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConceptId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CurvatureAfter")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("CurvatureBefore")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("QualityScore")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<string>("ThoughtSpaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("IX_LearningEvents_ConceptId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_LearningEvents_OccurredAt");

                    b.HasIndex("ThoughtSpaceId")
                        .HasDatabaseName("IX_LearningEvents_ThoughtSpaceId");

                    b.HasIndex("ConceptId", "OccurredAt")
                        .HasDatabaseName("IX_LearningEvents_ConceptTime");

                    b.ToTable("LearningEvents");
                });

            modelBuilder.Entity("Hazina.Core.Entities.Geometric.ThoughtSpace", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("GlobalCurvature")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("LearningVelocity")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("TunnelingCapability")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ThoughtSpaces_UserId");

                    b.HasIndex("UserId", "Domain")
                        .HasDatabaseName("IX_ThoughtSpaces_UserDomain");

                    b.ToTable("ThoughtSpaces");

                    b.HasData(
                        new
                        {
                            Id = "ts-example-programming",
                            CreatedAt = new DateTime(2026, 2, 20, 4, 0, 0, 0, DateTimeKind.Utc),
                            Dimensions = 12,
                            Domain = "programming",
                            GlobalCurvature = 0.85m,
                            LearningVelocity = 0m,
                            TunnelingCapability = 0.5m,
                            UpdatedAt = new DateTime(2026, 2, 20, 4, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "demo-user"
                        });
                });

            modelBuilder.Entity("Hazina.Core.Entities.Geometric.Concept", b =>
                {
                    b.HasOne("Hazina.Core.Entities.Geometric.ThoughtSpace", "ThoughtSpace")
                        .WithMany("Concepts")
                        .HasForeignKey("ThoughtSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThoughtSpace");
                });

            modelBuilder.Entity("Hazina.Core.Entities.Geometric.ConceptConnection", b =>
                {
                    b.HasOne("Hazina.Core.Entities.Geometric.Concept", "FromConcept")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("FromConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hazina.Core.Entities.Geometric.Concept", "ToConcept")
                        .WithMany("IncomingConnections")
                        .HasForeignKey("ToConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromConcept");

                    b.Navigation("ToConcept");
                });

            modelBuilder.Entity("Hazina.Core.Entities.Geometric.LearningEvent", b =>
                {
                    b.HasOne("Hazina.Core.Entities.Geometric.Concept", "Concept")
                        .WithMany("Events")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hazina.Core.Entities.Geometric.ThoughtSpace", "ThoughtSpace")
                        .WithMany("LearningHistory")
                        .HasForeignKey("ThoughtSpaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("ThoughtSpace");
                });

            modelBuilder.Entity("Hazina.Core.Entities.Geometric.Concept", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("IncomingConnections");

                    b.Navigation("OutgoingConnections");
                });

            modelBuilder.Entity("Hazina.Core.Entities.Geometric.ThoughtSpace", b =>
                {
                    b.Navigation("Concepts");

                    b.Navigation("LearningHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
