using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Hazina.AI.PromptManagement.Reflection;

/// <summary>
/// Reflection engine for analyzing prompt performance and generating improvement hypotheses
/// </summary>
public interface IReflectionEngine
{
    /// <summary>
    /// Generate a comprehensive reflection report for a prompt over a time period
    /// </summary>
    /// <param name="promptId">Prompt ID to analyze</param>
    /// <param name="startDate">Start of analysis period</param>
    /// <param name="endDate">End of analysis period</param>
    /// <param name="minRunsRequired">Minimum evaluation runs required (default: 10)</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Reflection report with patterns and improvement hypotheses</returns>
    Task<ReflectionReport> GenerateReportAsync(
        string promptId,
        DateTime startDate,
        DateTime endDate,
        int minRunsRequired = 10,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Get reflection report by ID
    /// </summary>
    /// <param name="reportId">Report ID</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Reflection report</returns>
    Task<ReflectionReport?> GetReportAsync(
        string reportId,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Get recent reflection reports for a prompt
    /// </summary>
    /// <param name="promptId">Prompt ID</param>
    /// <param name="limit">Maximum number of reports to retrieve</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>List of reflection reports</returns>
    Task<List<ReflectionReport>> GetReportHistoryAsync(
        string promptId,
        int limit = 10,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Analyze specific failure patterns and generate targeted hypotheses
    /// </summary>
    /// <param name="promptId">Prompt ID</param>
    /// <param name="patternIds">Specific pattern IDs to analyze</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>List of improvement hypotheses</returns>
    Task<List<ImprovementHypothesis>> AnalyzePatternsAsync(
        string promptId,
        List<string> patternIds,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Comprehensive reflection report
/// </summary>
public class ReflectionReport
{
    public string ReportId { get; set; } = Guid.NewGuid().ToString();
    public string PromptId { get; set; } = string.Empty;
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Evaluation summary
    public int TotalRuns { get; set; }
    public double SuccessRate { get; set; }  // 0.0 to 1.0
    public Dictionary<string, double> AverageMetrics { get; set; } = new();  // metric → avg score

    // Pattern analysis
    public List<FailurePatternSummary> FailurePatterns { get; set; } = new();
    public List<SuccessPatternSummary> SuccessPatterns { get; set; } = new();

    // Improvement hypotheses
    public List<ImprovementHypothesis> ImprovementHypotheses { get; set; } = new();

    // Overall assessment
    public string OverallAssessment { get; set; } = string.Empty;  // LLM-generated summary
    public Dictionary<string, object> Metadata { get; set; } = new();
}

/// <summary>
/// Failure pattern summary in reflection report
/// </summary>
public class FailurePatternSummary
{
    public string PatternId { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public double Frequency { get; set; }  // 0.0 to 1.0
    public int Occurrences { get; set; }
    public List<string> Examples { get; set; } = new();  // Sample queries
    public string RootCause { get; set; } = string.Empty;  // LLM-analyzed root cause
    public List<string> AffectedMetrics { get; set; } = new();
    public double Impact { get; set; }  // 0.0 to 1.0 - impact on overall performance
}

/// <summary>
/// Success pattern summary in reflection report
/// </summary>
public class SuccessPatternSummary
{
    public string PatternId { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public double Frequency { get; set; }  // 0.0 to 1.0
    public int Occurrences { get; set; }
    public List<string> Examples { get; set; } = new();
    public List<string> KeyFactors { get; set; } = new();  // What makes these succeed
    public Dictionary<string, double> MetricImpact { get; set; } = new();  // metric → avg score
}

/// <summary>
/// Improvement hypothesis generated by reflection engine
/// </summary>
public class ImprovementHypothesis
{
    public string HypothesisId { get; set; } = Guid.NewGuid().ToString();
    public string Hypothesis { get; set; } = string.Empty;  // What to change
    public string Rationale { get; set; } = string.Empty;  // Why this will help
    public double ExpectedImpact { get; set; }  // 0.0 to 1.0 - expected improvement magnitude
    public string Priority { get; set; } = "medium";  // "low" | "medium" | "high" | "critical"

    // What patterns this hypothesis addresses
    public List<string> AddressedPatterns { get; set; } = new();

    // Specific changes to apply
    public List<SuggestedChange> SuggestedChanges { get; set; } = new();

    // Confidence in this hypothesis
    public double Confidence { get; set; }  // 0.0 to 1.0

    // Related metrics expected to improve
    public List<string> TargetMetrics { get; set; } = new();
}

/// <summary>
/// Specific suggested change within a hypothesis
/// </summary>
public class SuggestedChange
{
    public string ChangeType { get; set; } = string.Empty;  // "Add" | "Remove" | "Modify" | "Restructure"
    public string Section { get; set; } = string.Empty;  // Which part of prompt (e.g., "instructions", "examples", "constraints")
    public string CurrentValue { get; set; } = string.Empty;
    public string ProposedValue { get; set; } = string.Empty;
    public string Reason { get; set; } = string.Empty;
}
