using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Hazina.AI.PromptManagement.Reflection;

namespace Hazina.AI.PromptManagement.Rewriter;

/// <summary>
/// Prompt rewriter that applies improvement hypotheses to generate new prompt versions
/// </summary>
public interface IPromptRewriter
{
    /// <summary>
    /// Apply an improvement hypothesis to generate a prompt proposal
    /// </summary>
    /// <param name="promptId">Prompt ID to improve</param>
    /// <param name="hypothesis">Improvement hypothesis to apply</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Generated prompt proposal</returns>
    Task<PromptProposal> ApplyHypothesisAsync(
        string promptId,
        ImprovementHypothesis hypothesis,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Apply multiple hypotheses to generate a single combined proposal
    /// </summary>
    /// <param name="promptId">Prompt ID to improve</param>
    /// <param name="hypotheses">List of hypotheses to apply</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Combined prompt proposal</returns>
    Task<PromptProposal> ApplyMultipleHypothesesAsync(
        string promptId,
        List<ImprovementHypothesis> hypotheses,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Generate A/B test variants for a hypothesis
    /// </summary>
    /// <param name="promptId">Prompt ID</param>
    /// <param name="hypothesis">Hypothesis to test</param>
    /// <param name="variantCount">Number of variants to generate (default: 2)</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>List of variant proposals</returns>
    Task<List<PromptProposal>> GenerateVariantsAsync(
        string promptId,
        ImprovementHypothesis hypothesis,
        int variantCount = 2,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Calculate semantic similarity between original and proposed prompts
    /// </summary>
    /// <param name="originalTemplate">Original prompt template</param>
    /// <param name="proposedTemplate">Proposed prompt template</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Similarity score (0.0 to 1.0)</returns>
    Task<double> CalculateSimilarityAsync(
        string originalTemplate,
        string proposedTemplate,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Validate that a proposal meets semantic drift thresholds
    /// </summary>
    /// <param name="proposal">Proposal to validate</param>
    /// <param name="minSimilarity">Minimum allowed similarity (default: 0.85)</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>True if proposal is within acceptable similarity bounds</returns>
    Task<bool> ValidateSemanticSimilarityAsync(
        PromptProposal proposal,
        double minSimilarity = 0.85,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Prompt improvement proposal generated by the rewriter
/// </summary>
public class PromptProposal
{
    public string ProposalId { get; set; } = Guid.NewGuid().ToString();
    public string PromptId { get; set; } = string.Empty;
    public string CurrentVersion { get; set; } = string.Empty;  // Current version ID
    public string ProposedTemplate { get; set; } = string.Empty;
    public string ProposedVersionId { get; set; } = string.Empty;  // SHA-256 of proposed template

    // What changed
    public List<PromptChange> Changes { get; set; } = new();

    // Why this proposal was created
    public string Rationale { get; set; } = string.Empty;
    public double ExpectedImprovement { get; set; }  // 0.0 to 1.0

    // Proposal metadata
    public string Status { get; set; } = "pending";  // "pending" | "approved" | "rejected" | "deployed" | "rolled_back"
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public string CreatedBy { get; set; } = "system:rewriter";

    // Source hypothesis
    public string? ReflectionReportId { get; set; }
    public List<string> HypothesisIds { get; set; } = new();  // Hypotheses applied in this proposal

    // Semantic similarity
    public double SemanticSimilarity { get; set; }  // 0.0 to 1.0 - similarity to original

    // Metadata
    public Dictionary<string, object> Metadata { get; set; } = new();
}

/// <summary>
/// Represents a single change in a prompt proposal
/// </summary>
public class PromptChange
{
    public string ChangeId { get; set; } = Guid.NewGuid().ToString();
    public string Type { get; set; } = string.Empty;  // "Add" | "Remove" | "Modify" | "Restructure"
    public string Section { get; set; } = string.Empty;  // "instructions" | "examples" | "constraints" | "format"
    public string OldValue { get; set; } = string.Empty;
    public string NewValue { get; set; } = string.Empty;
    public string Reason { get; set; } = string.Empty;
    public int LineStart { get; set; }  // Line number where change starts (for diff display)
    public int LineEnd { get; set; }  // Line number where change ends
}

/// <summary>
/// Result of applying a hypothesis
/// </summary>
public class RewriteResult
{
    public bool Success { get; set; }
    public PromptProposal? Proposal { get; set; }
    public string? ErrorMessage { get; set; }
    public List<string> Warnings { get; set; } = new();
}
